language: node_js
node_js:
  - "10"
  - "12"
before_install:
  - yarn global add webpack koa-cola
  - cd app_test
  - yarn
  - cd ../
  - yarn add mongodb-download@2.2.3
  # - yarn config set ignore-engines true
after_success: npm run coverage
