language: node_js
node_js:
  - "10"
  - "8"
  - "7.10.1"
before_install:
  - npm i -g webpack koa-cola
  - cd app_test
  - npm i
  - cd ../
  - npm i mongodb-download@2.2.3
  - yarn config set ignore-engines true
after_success: npm run coverage
